// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package queries

import (
	"context"
)

type Querier interface {
	DeleteWelcome(ctx context.Context, guildID string) error
	GetV(ctx context.Context, k string) (string, error)
	GetWelcome(ctx context.Context, guildID string) (Welcome, error)
	InsertWelcome(ctx context.Context, arg InsertWelcomeParams) error
	SetWelcomeChannel(ctx context.Context, arg SetWelcomeChannelParams) error
	SetWelcomeImageName(ctx context.Context, arg SetWelcomeImageNameParams) error
	SetWelcomeImageSubtitle(ctx context.Context, arg SetWelcomeImageSubtitleParams) error
	SetWelcomeImageTitle(ctx context.Context, arg SetWelcomeImageTitleParams) error
	SetWelcomeMessageText(ctx context.Context, arg SetWelcomeMessageTextParams) error
	SetWelcomeMessageType(ctx context.Context, arg SetWelcomeMessageTypeParams) error
	UpsertKV(ctx context.Context, arg UpsertKVParams) error
}

var _ Querier = (*Queries)(nil)
